[package]
name = "spell-bench"
version = "0.2.0"
authors = ["Jesse A. Tov <jesse.tov@gmail.com>"]
build = "build.rs"
edition = "2018"

[features]
unstable = []

[dependencies]
lazy_static = "1.4"

[build-dependencies]
rustc_version = "0.2"
